### PR TITLE
[test] Refactor saithriftv2 Makefile

### PR DESCRIPTION
**Pull request by kcudnik**
Many changes to not rebuild everything each time, install should only copy files if they are different

### CODE REVIEW

**Comment by chrispsommers** [comment]
@kcudnik I did a "regression test" by changing DASH to use your SAI branch `mrefactor`. It builds but the python tests all fail with `No module named 'sai_thrift.sai_adapter'`. I did not take time to find root cause but it's possible something got omitted from the saithrift build. I noticed `make all` takes half the time now, which is suspicious.

You can try out my branch: https://github.com/chrispsommers/DASH/tree/test-sai-kcudnik-mrefactor

In three consoles:
```
make clean;make all; make run-switch
make run-saithrift-server # do after above running
make run-all-tests # do after above
```


```
$ make run-saithrift-ptftests 
./disable_veth_ipv6.sh
Disable IPv6 to suppress Linux control plane noise
net.ipv6.conf.veth0.disable_ipv6 = 1
net.ipv6.conf.veth0.autoconf = 0
net.ipv6.conf.veth0.accept_ra = 0
net.ipv6.conf.veth0.accept_ra_pinfo = 0
net.ipv6.conf.veth0.router_solicitations = 0
net.ipv6.conf.veth1.disable_ipv6 = 1
net.ipv6.conf.veth1.autoconf = 0
net.ipv6.conf.veth1.accept_ra = 0
net.ipv6.conf.veth1.accept_ra_pinfo = 0
net.ipv6.conf.veth1.router_solicitations = 0
net.ipv6.conf.veth2.disable_ipv6 = 1
net.ipv6.conf.veth2.autoconf = 0
net.ipv6.conf.veth2.accept_ra = 0
net.ipv6.conf.veth2.accept_ra_pinfo = 0
net.ipv6.conf.veth2.router_solicitations = 0
net.ipv6.conf.veth3.disable_ipv6 = 1
net.ipv6.conf.veth3.autoconf = 0
net.ipv6.conf.veth3.accept_ra = 0
net.ipv6.conf.veth3.accept_ra_pinfo = 0
net.ipv6.conf.veth3.router_solicitations = 0
docker run -u root --network=host --rm -w /tests/ -it  \
-w /tests/ \
local/dash-saithrift-client:latest \
./functional/ptf/run-tests.sh
+ ptf --test-dir ./functional/ptf --pypath /SAI/ptf --interface 0@veth1 --interface 1@veth3 --test-case-timeout=1800 '--test-params=connection='\''tcp'\'';target='\''bmv2'\'';traffic_check='\''bidir'\'';'
/usr/local/lib/python3.8/dist-packages/ptf-0.9.3-py3.8.egg/EGG-INFO/scripts/ptf:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Using packet manipulation module: ptf.packet_scapy
Traceback (most recent call last):
  File "/usr/local/bin/ptf", line 4, in <module>
    __import__('pkg_resources').run_script('ptf==0.9.3', 'ptf')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/ptf-0.9.3-py3.8.egg/EGG-INFO/scripts/ptf", line 710, in <module>
    test_modules = load_test_modules(config)
  File "/usr/local/lib/python3.8/dist-packages/ptf-0.9.3-py3.8.egg/EGG-INFO/scripts/ptf", line 547, in load_test_modules
    mod = imp.load_module(modname, *imp.find_module(modname, [root]))
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./functional/ptf/sai_dash_utils.py", line 20, in <module>
    from sai_base_test import *
  File "/SAI/ptf/sai_base_test.py", line 41, in <module>
    from sai_utils import *
  File "/SAI/ptf/sai_utils.py", line 29, in <module>
    from sai_thrift.sai_adapter import *
ModuleNotFoundError: No module named 'sai_thrift.sai_adapter'
make: *** [Makefile:478: run-saithrift-ptftests] Error 1
```

**Comment by kcudnik** [comment]
intresting, its too late for me today, i will  try this tommorow, my local builds passes XD

**Comment by kcudnik** [comment]
what i do is this:
 make run-switch # terminal 1
 make run-saithrift-server # terminal 2
 make run-saithrift-ptftests # terminal 3
in 3 different consoles

**Comment by kcudnik** [comment]
before that: make p4; make sai

**Comment by chrispsommers** [comment]
I'll try again in a new env in case I have contaminated mine. You ran `make saithriift-server` but not `make saithrift-client` which is where those missing libraries are needed. They're copied from the prior saithrift-server build libraries. `make all` would rebuild the client. When in doubt, `make clean;make all`

**Comment by kcudnik** [comment]
will try tommorow

**Comment by kcudnik** [comment]
> @kcudnik I did a "regression test" by changing DASH to use your SAI branch `mrefactor`. It builds but the python tests all fail with `No module named 'sai_thrift.sai_adapter'`. I did not take time to find root cause but it's possible something got omitted from the saithrift build. I noticed `make all` takes half the time now, which is suspicious.

compilation time is intended to be shortened, notice that i removed "clean" from all, which was causing rebuild everyghing each time,i will investigate today why this is failing, i also have other optiomizations in DASH repo in makefiles that also will impvorve quality and build time, but i need to start with this one, will let you know after investigation

**Comment by kcudnik** [comment]
ok, i reproduced this locally, i had to miss something, since if i call "make all" twice then it works and all tests are passing :D

it actually dont need to be make all, just "make docker-saithrift-client docker-saichallenger-client", im investigating

ps. i was able to modify some makefiles to make everything compile as host user, so no root files are created, and no chmod needed

**Comment by chrispsommers** [comment]
@kcudnik Glad you're able to reproduce, I'm sure you solve it soon. I'm eager to see your makefile improvements to eliminate `chmod`, that was a hack and deserves fixing. Thanks!

**Comment by kcudnik** [comment]
so i found problem partally, when executee 1st timee make saithrift-server and then second time it gives this (from vimdiff)
```
  427 creating saithrift-0.9/gen-py^M                                                                      63 creating saithrift-0.9/gen-py^M
  428 creating saithrift-0.9/gen-py/sai^M                                                                  64 creating saithrift-0.9/gen-py/sai^M
  429 making hard links in saithrift-0.9...^M                                                              65 making hard links in saithrift-0.9...^M
  430 hard linking setup.py -> saithrift-0.9^M                                                             66 hard linking setup.py -> saithrift-0.9^M
  431 hard linking gen-py/sai/__init__.py -> saithrift-0.9/gen-py/sai^M                                    67 hard linking gen-py/sai/__init__.py -> saithrift-0.9/gen-py/sai^M
  432 hard linking gen-py/sai/constants.py -> saithrift-0.9/gen-py/sai^M                                   68 hard linking gen-py/sai/constants.py -> saithrift-0.9/gen-py/sai^M
      -------------------------------------------------------------------------------------------------    69 hard linking gen-py/sai/sai_adapter.py -> saithrift-0.9/gen-py/sai^M
  433 hard linking gen-py/sai/sai_headers.py -> saithrift-0.9/gen-py/sai^M                                 70 hard linking gen-py/sai/sai_headers.py -> saithrift-0.9/gen-py/sai^M
  434 hard linking gen-py/sai/sai_rpc.py -> saithrift-0.9/gen-py/sai^M                                     71 hard linking gen-py/sai/sai_rpc.py -> saithrift-0.9/gen-py/sai^M
  435 hard linking gen-py/sai/ttypes.py -> saithrift-0.9/gen-py/sai^M                                      72 hard linking gen-py/sai/ttypes.py -> saithrift-0.9/gen-py/sai^M
  436 creating dist^M                                                                                         ------------------------------------------------------------------------------------------------
  ```

i don't exactly know why first time sai_adapter.py is not hard linked, i probably messed up some dependency

**Comment by kcudnik** [comment]
i found and fixed the issue, adapter was installed after setup.py was called, i fixed the order and it works now

can you also do 1 more check to confirm ?

**Comment by chrispsommers** [comment]
@kcudnik I think you fixed it! It built and passed all tests. It builds in half the time too, you da man!

**Comment by kcudnik** [comment]
yea, i think it will be good now, it also could be improved further, because python setup.py command regenerate packages always so they don't check the contents, but the entire build is much faster, 

level 1 makefile monk unlocked

there is one small detail that i will also fix later on, the adapter is generated on /usr/include/sai which is a hack in DASH repo to copy those headers files, but it can be generated using locally SAi headers, results will be the seme, unless some vendors are using that on their internal sai headers installed in /usr/include/sai, originally this was added by @richardyu-ms on 16c11ee7

@richardyu-ms  can you elaboreate why https://github.com/opencomputeproject/SAI/pull/1881/files#diff-bc1c915b7f6283ed29595639229e6ca7102f1756ae802870c29fe9148ceb36d0R10 and bc1c915b7f6283ed29595639229e6ca7102f1756ae802870c29fe9148ceb36d0R12 and https://github.com/opencomputeproject/SAI/pull/1881/files#diff-bc1c915b7f6283ed29595639229e6ca7102f1756ae802870c29fe9148ceb36d0R89 are generated from I$(SAI_HEADER_DIR) which is /usr/include/sai instead of ../../inc ?? was taht done for some particular vendor ? why not use local SAI repo headers for generation? when next tot that explicy experimental headers are added in ../../experimental ?

@chrispsommers after that i will update SAI submodule in DAHS along with Makefile improvements on DASH

**Comment by richardyu-ms** [comment]
> yea, i think it will be good now, it also could be improved further, because python setup.py command regenerate packages always so they don't check the contents, but the entire build is much faster,
> 
> level 1 makefile monk unlocked
> 
> there is one small detail that i will also fix later on, the adapter is generated on /usr/include/sai which is a hack in DASH repo to copy those headers files, but it can be generated using locally SAi headers, results will be the seme, unless some vendors are using that on their internal sai headers installed in /usr/include/sai, originally this was added by @richardyu-ms on [16c11ee](https://github.com/opencomputeproject/SAI/commit/16c11ee7062e630f1eaf4bb3e44d31ab58eafa5b)
> 
> @richardyu-ms can you elaboreate why https://github.com/opencomputeproject/SAI/pull/1881/files#diff-bc1c915b7f6283ed29595639229e6ca7102f1756ae802870c29fe9148ceb36d0R10 and bc1c915b7f6283ed29595639229e6ca7102f1756ae802870c29fe9148ceb36d0R12 and https://github.com/opencomputeproject/SAI/pull/1881/files#diff-bc1c915b7f6283ed29595639229e6ca7102f1756ae802870c29fe9148ceb36d0R89 are generated from I$(SAI_HEADER_DIR) which is /usr/include/sai instead of ../../inc ?? was taht done for some particular vendor ? why not use local SAI repo headers for generation? when next tot that explicy experimental headers are added in ../../experimental ?
> 
> @chrispsommers after that i will update SAI submodule in DAHS along with Makefile improvements on DASH

I think you also marked the related code with
```
# TODO should depend on ../../inc/sai*.h ../../experimental/sai*.h and not /usr/include/sai/sai*.h
```
@kcudnik.  Yes, you are right, I changed it to dependence on the place that SDK installed but not the SAI repo located. This is because the vendor's SAI header might be different. like the headers in ``inc`` and ``experimental ``, vendor might add something in ``expermental`` and headers in ``inc`` might be updated accordingly, I recall that happened in the latest SAI version.
Generated RPC API can only work with matched SDK and SDK depends on headers.

**Comment by kcudnik** [comment]
yea, that's correct that sai headers must match, so should we leave this as is or should we actually change it to SAI headers only, or add some specific comment why this is done this way ?

**Comment by richardyu-ms** [comment]
> yea, that's correct that sai headers must match, so should we leave this as is or should we actually change it to SAI headers only, or add some specific comment why this is done this way ?

cause this situation not always happen, when this happens it will break the tests and not ver easy to fix them, and after vendor updated their SAI headers, they always keep them aline. I prefer to add some comments for the purpose of doing that.

**Pull request merged**
