### PR TITLE
Tunnel Term Types - fixed the description for types and validity checks for mask attributes

### PR DESCRIPTION
**Pull request by mholankar**
Fixed the comments for the tunnel types

### CODE REVIEW

**Comment by mholankar** [comment]
@mikeberesford please take a look

**Comment by mikeberesford** [comment]
This looks right to me, but definitely needs to be discussed at the SAI community meeting. @rlhui can we get this on the agenda for next week?

**Comment by rlhui** [comment]
> This looks right to me, but definitely needs to be discussed at the SAI community meeting. @rlhui can we get this on the agenda for next week?

yes

**Review by kcudnik — APPROVED** [review]

**Comment by mholankar** [comment]
Moving this PR to https://github.com/opencomputeproject/SAI/pull/1848

**Pull request closed without merging**
