### PR TITLE
Change ACL address key to prefix list

### PR DESCRIPTION
**Pull request by marian-pritsak**
Signed-off-by: Marian Pritsak <marianp@mellanox.com>

### CODE REVIEW

**Comment by marian-pritsak** [comment]
Depends on https://github.com/opencomputeproject/SAI/pull/1629

**Comment by lguohan** [comment]
i am not able to cherry-pick this  #1629 to this branch?

**Comment by lguohan** [comment]
can you create a pr on this branch?

**Review by prsunny — APPROVED** [review]

**Comment by lguohan** [comment]
@marian-pritsak

**Comment by marian-pritsak** [comment]
Created a PR for dependency to dash branch https://github.com/opencomputeproject/SAI/pull/1639

@lguohan

**Pull request merged**
