### PR TITLE
Add NVGRE tunnel

### PR DESCRIPTION
**Pull request by marian-pritsak**
Signed-off-by: Marian Pritsak <marianp@mellanox.com>

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]

**Comment by rlhui** [comment]
@JaiOCP , @ashutosh-agrawal , @rck-innovium  - please help review/sign-off?  Thanks.

**Review by JaiOCP — COMMENTED** [review]
Is there any impact if NVGRE mappers are created and assigned at switch level for tunnel encapsulated/decap ?
API will not prevent switch level configuration for NVGRE.

**Review by ashutosh-agrawal — APPROVED** [review]
LGTM

**Comment by marian-pritsak** [comment]
> Is there any impact if NVGRE mappers are created and assigned at switch level for tunnel encapsulated/decap ?
> API will not prevent switch level configuration for NVGRE.

Switch level mappers are applied per tunnel type (SAI_SWITCH_TUNNEL_ATTR_TUNNEL_TYPE), and whatever will be applied for NVGRE at switch level, will not affect the rest.

**Comment by JaiOCP** [comment]
> > Is there any impact if NVGRE mappers are created and assigned at switch level for tunnel encapsulated/decap ?
> > API will not prevent switch level configuration for NVGRE.
> 
> Switch level mappers are applied per tunnel type (SAI_SWITCH_TUNNEL_ATTR_TUNNEL_TYPE), and whatever will be applied for NVGRE at switch level, will not affect the rest.

So we are saying switch level configuration for NVGRE is supported as well. Please confirm.

**Comment by marian-pritsak** [comment]
> > > Is there any impact if NVGRE mappers are created and assigned at switch level for tunnel encapsulated/decap ?
> > > API will not prevent switch level configuration for NVGRE.
> > 
> > 
> > Switch level mappers are applied per tunnel type (SAI_SWITCH_TUNNEL_ATTR_TUNNEL_TYPE), and whatever will be applied for NVGRE at switch level, will not affect the rest.
> 
> So we are saying switch level configuration for NVGRE is supported as well. Please confirm.

Yes, that is correct

**Review by JaiOCP — APPROVED** [review]

**Pull request merged**
