### PR TITLE
Add SG/XG acronyms

### PR DESCRIPTION
**Pull request by stcheng**

### CODE REVIEW

**Comment by kcudnik** [comment]
not much helpful XD

**Comment by stcheng** [comment]
this info is enough for googling 🔍

**Comment by kcudnik** [comment]
i didn't found exact explanation, but seems like S i source (ip), and can be * as any, and G i multicast group ip

**Comment by lguohan** [comment]
SG is the source specific multicast
*G is the source nonspecific multicast

**Comment by kcudnik** [comment]
Can you add Guohan description to acronyms ?

**Comment by stcheng** [comment]
@kcudnik updated.

**Pull request merged**
