### PR TITLE
Fixed conditions for ENCAP_MAPPERS and DECAP_MAPPERS

### PR DESCRIPTION
**Pull request by IGordynskyi**
Fixed conditions for SAI_TUNNEL_ATTR_ENCAP_MAPPERS and SAI_TUNNEL_ATTR_DECAP_MAPPERS tunnel attributes to attach to tunnel different types of mappers

### CODE REVIEW

**Comment by IGordynskyi** [comment]
In current conditions for tunnel encap and decap mappers only SAI_TUNNEL_MAP_TYPE_OECN_TO_UECN and SAI_TUNNEL_MAP_TYPE_UECN_OECN_TO_OECN mappers can be attached to tunnel. 
Removed condition section from tunnel encap and decap mappers to support attaching all types of mappers.

**Comment by kcudnik** [comment]
I approved only for code change, but FYI, if you remove those conditions, then those 2 attributes will be **mandatory** every time tunnel will be created

**Comment by itaibaz** [comment]
i am not sure we want to make these attributes always mandatory. perhaps then we should remove the mandatory clause and give a default of empty list ? (but then we will miss the check that if user modes are defined, a map must be attached)

**Comment by vitaliy-senchyshyn** [comment]
@itaibaz If leave the code as is how the mappers of other types can be attached to the tunnel? We're trying to figure out how to connect bridge-to-vni mappers to the tunnel and looks like with the current definitions we can't do this.

**Comment by IGordynskyi** [comment]
@itaibaz I have pushed changes according to your comment. Could you please review?

**Comment by IGordynskyi** [comment]
BTW, there are other inconsistencies in attributes definitions:
1. Are SAI_TUNNEL_ATTR_UNDERLAY_INTERFACE and SAI_TUNNEL_ATTR_OVERLAY_INTERFACE attributes valid only on IPINIP and IPINIP_GRE types?
```
     * @type sai_object_id_t
     * @flags MANDATORY_ON_CREATE | CREATE_ONLY
     * @objects SAI_OBJECT_TYPE_ROUTER_INTERFACE
     * @condition SAI_TUNNEL_ATTR_TYPE == SAI_TUNNEL_TYPE_IPINIP or SAI_TUNNEL_ATTR_TYPE == SAI_TUNNEL_TYPE_IPINIP_GRE
```
2. SAI_TUNNEL_ATTR_DECAP_TTL_MODE and SAI_TUNNEL_ATTR_DECAP_DSCP_MODE are valid only on IPINIP and IPINIP_GRE types and on encap TTL and DSCP modes don't have such conditions.

**Comment by karthik-krishnamurthy** [comment]
@IGordynskyi Yes seems the attribute conditions have not been updated to accommodate the newer tunnel types and other changes which have happened in this file over time.

**Comment by IGordynskyi** [comment]
> @IGordynskyi Yes seems the attribute conditions have not been updated to accommodate the newer tunnel types and other changes which have happened in this file over time.

@karthik-krishnamurthy should that be fixed in scope of this PR?

**Comment by IGordynskyi** [comment]
@kcudnik since this pull request is approved by you and @itaibaz could you please merge it.

**Comment by kcudnik** [comment]
Merged

**Comment by IGordynskyi** [comment]
Thanks!

**Pull request merged**
