### PR TITLE
Add new enum to support 8 lanes breakout mode

### PR DESCRIPTION
**Pull request by rajkumar38**
Add new breakout mode enum to "sai_port_breakout_mode_type_t",

/** 8 lanes breakout Mode */
SAI_PORT_BREAKOUT_MODE_TYPE_8_LANE = 3,

### CODE REVIEW

**Comment by rajkumar38** [comment]
@kcudnik 
Can you suggest how to fix this WARNING ? I'm excluding "SAI_PORT_BREAKOUT_MODE_TYPE_MAX " in ancestry.pl.
```
WARNING: Both enums have the same value SAI_PORT_BREAKOUT_MODE_TYPE_8_LANE and SAI_PORT_BREAKOUT_MODE_TYPE_MAX = 0x00000003
```

**Comment by kcudnik** [comment]
You need to add exception for max value in checking script

**Comment by rajkumar38** [comment]
> You need to add exception for max value in checking script

Pls review.

**Review by kcudnik — APPROVED** [review]

**Comment by tjchadaga** [comment]
Discussed in SAI meeting on 5/9, @prgeor , @JaiOCP - please help review/sign off

**Review by JaiOCP — APPROVED** [review]

**Comment by rajkumar38** [comment]
@JaiOCP, Regarding your question on standards. There are different IEEE 802.3(https://en.wikipedia.org/wiki/Terabit_Ethernet) standards for defining Terabit Ethernet with different speeds. This captures the max lanes and speed per lane but doesn't explicitly talk about break-out. Its up-to vendor capability.

**Review by prgeor — APPROVED** [review]

**Pull request merged**
