### PR TITLE
add SAI_PORT_BREAKOUT_MODE_TYPE_8_LANE

### PR DESCRIPTION
**Pull request by chuzirui**
add SAI_PORT_BREAKOUT_MODE_TYPE_8_LANE to sai_port_breakout_mode_type_t

### CODE REVIEW

**Comment by kcudnik** [comment]
```
WARNING: Both enums have the same value SAI_PORT_BREAKOUT_MODE_TYPE_8_LANE and SAI_PORT_BREAKOUT_MODE_TYPE_MAX = 0x00000003
```

you will need to exclude SAI_PORT_BREAKOUT_MODE_TYPE_MAX in ancestry.pl

**Comment by kcudnik** [comment]
Do not edit history file, ether fix this in ancestry.pl

**Comment by kcudnik** [comment]
With latest change you don't need to change history file, please rever

**Comment by rlhui** [comment]
@chuzirui , would you like to discuss/present this in SAI meeting?

**Comment by rajkumar38** [comment]
@chuzirui, We need 8_LANE support for Marvell ASIC. Do you plan to discuss this PR in community meeting ?

**Comment by kcudnik** [comment]
please revert history file change

**Comment by tjchadaga** [comment]
@chuzirui - There is some interest from other vendors in adding this capability. Would you like to get this PR reviewed in the SAI community meeting?

**Comment by tjchadaga** [comment]
Changes already merged with https://github.com/opencomputeproject/SAI/pull/2009

**Pull request closed without merging**
