### PR TITLE
SAI 1.13.3 Release notes

### PR DESCRIPTION
**Pull request by kannankvs**
SAI version 1.13.3 Release notes

### CODE REVIEW

**Comment by kcudnik** [comment]
please sign commit to satisfy DCO check

**Comment by zhangyanzhao** [comment]
@yxieca  @rlhui can you please help to review this PR? Thanks.

**Comment by yxieca** [comment]
@kannankvs can you check the DCO checker failure?

**Comment by kannankvs** [comment]
This PR has a DCO error, and we tried to fix it. However we were unable to remove the DCO error. Hence we are closing this PR and raised a new [PR#1953](https://github.com/opencomputeproject/SAI/pull/1953)

**Pull request closed without merging**
