### PR TITLE
add STP_PORT object and CRUD api for it

### PR DESCRIPTION
**Pull request by lguohan**

### CODE REVIEW

**Comment by lguohan** [comment]
@AshokDaparthi and @itaibaz , please review

**Comment by itaibaz** [comment]
i think we should have a RO stp_port list
SAI_STP_ATTR_PORT_LIST

**Comment by lguohan** [comment]
@itaibaz , added

**Comment by itaibaz** [comment]
Re
 +     * @objects SAI_OBJECT_TYPE_PORT
 +    SAI_STP_ATTR_PORT_LIST,
I think the port list should be objects of type SAI_OBJECT_TYPE_STP_PORT and not SAI_OBJECT_TYPE_PORT

**Comment by lguohan** [comment]
test it

**Comment by lguohan** [comment]
changed to TYPE_STP_PORT

**Pull request merged**
