### PR TITLE
Add auto generate attr for acl user defined fields

### PR DESCRIPTION
**Pull request by kcudnik**

### CODE REVIEW

**Comment by kcudnik** [comment]
This will generate over 500 attributes for user defined field since range is 0xFF, but probably you don't need so many at all, please let me know if for example 10 or 5 is enough since i would like to limit this attribute generation to minimum if they are not necessary

**Comment by yakivh** [comment]
I would say that 10 is enough 
Thanks

**Comment by lguohan** [comment]
:shipit:

**Comment by yakivh** [comment]
@kcudnik can you please update the tags to have a type _sai_object_id_t_ for _SAI_ACL_TABLE_ATTR_USER_DEFINED_FIELD_GROUP_MIN_
and _sai_acl_field_data_t sai_uint8_list_t_ for _SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_MIN_ ?

I haven't managed to create a PR because metadata checker complains in the following way:
```
invalid enum specified acl field 'sai_acl_field_data_t sai_uint8_list_t' on SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_MIN
sai_acl_field_data_t sai_uint8_list_t == SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_MIN not ending on enum name UINT8_LIST
invalid enum specified acl field 'sai_acl_field_data_t sai_uint8_list_t' on SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_1
sai_acl_field_data_t sai_uint8_list_t == SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_1 not ending on enum name UINT8_LIST
invalid enum specified acl field 'sai_acl_field_data_t sai_uint8_list_t' on SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_2
sai_acl_field_data_t sai_uint8_list_t == SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_2 not ending on enum name UINT8_LIST
invalid enum specified acl field 'sai_acl_field_data_t sai_uint8_list_t' on SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_3
sai_acl_field_data_t sai_uint8_list_t == SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_3 not ending on enum name UINT8_LIST
invalid enum specified acl field 'sai_acl_field_data_t sai_uint8_list_t' on SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_4
sai_acl_field_data_t sai_uint8_list_t == SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_4 not ending on enum name UINT8_LIST
invalid enum specified acl field 'sai_acl_field_data_t sai_uint8_list_t' on SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_5
sai_acl_field_data_t sai_uint8_list_t == SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_5 not ending on enum name UINT8_LIST
invalid enum specified acl field 'sai_acl_field_data_t sai_uint8_list_t' on SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_6
sai_acl_field_data_t sai_uint8_list_t == SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_6 not ending on enum name UINT8_LIST
invalid enum specified acl field 'sai_acl_field_data_t sai_uint8_list_t' on SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_7
sai_acl_field_data_t sai_uint8_list_t == SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_7 not ending on enum name UINT8_LIST
invalid enum specified acl field 'sai_acl_field_data_t sai_uint8_list_t' on SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_8
sai_acl_field_data_t sai_uint8_list_t == SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_8 not ending on enum name UINT8_LIST
invalid enum specified acl field 'sai_acl_field_data_t sai_uint8_list_t' on SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_9
sai_acl_field_data_t sai_uint8_list_t == SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_9 not ending on enum name UINT8_LIST
```

As far as I understand, it should work in the following way:
ACL Table gets the UDF Group object id. That is the information about offset and a length (via UDFs from this UDF Group)
ACL Entry gets the array of actual data to be matched

Is it possible to add these commits to 1.0 branch? 

Thanks

**Comment by kcudnik** [comment]
This is already merged to master, if you want to push those changes to some other branch please generate PR for that

**Comment by kcudnik** [comment]
And also not sure what you are trying to do since you are getting those errors

**Comment by yakivh** [comment]
@knudnic, what I'm trying to do is to change the headers to something like the following:
  ```
    /**
     * @brief User Defined Field Groups
     *
     * @type sai_object_id_t
     * @flags CREATE_ONLY
     * @allownull true
     * @default SAI_NULL_OBJECT_ID
     * @range SAI_ACL_USER_DEFINED_FIELD_ATTR_ID_RANGE
     */
    SAI_ACL_TABLE_ATTR_USER_DEFINED_FIELD_GROUP_MIN,

	...
	
    /**
     * @brief User Defined Field data for the UDF Groups in ACL Table
     *
     * @type sai_acl_field_data_t sai_uint8_list_t
     * @flags CREATE_AND_SET
     * @default disabled
     * @range SAI_ACL_USER_DEFINED_FIELD_ATTR_ID_RANGE
     */
    SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_MIN,
```

Please, see the motivation in my previous comment
When I try to run metadata over such header I receive the errors

Can you please suggest how to do this change?

Thanks

**Comment by kcudnik** [comment]
those min/max attributes in ACL_TABLE should be bool since it's indicating whether acl tabe is using this attribute. Actual object_is is used in ACL_ENTRY in SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_MIN .. SAI_ACL_ENTRY_ATTR_USER_DEFINED_FIELD_GROUP_MAX

**Pull request merged**
