### PR TITLE
Change in saifdb.h for CRUD. 

### PR DESCRIPTION
**Pull request by atitjain**
This is proposed as part of CRUD changes. The flush call is not one of the quad APIs. In stead, I remember during nexthop group and other CRUD change discussions we brought up the notion of bulk APIs. I feel
the bulk delete should be able to take care of the flush.

### CODE REVIEW

**Comment by lguohan** [comment]
@AshokDaparthi , can you comment?

**Comment by kcudnik** [comment]
To make it compile remove FDB_FLUSH from object_type enum since you removed attribute

**Comment by AshokDaparthi** [comment]
@atitjain @lguohan - Intention of these flush API's is to simplify the flush logic when STP state change etc. Instead of sending the FDB entries to removed as bulk or individual entry based on port, vlan , port+vlan or all, they can indicate just port oid, vlan or etc. Then underlying SDK's or hardware will delete those entries. this will be much faster than deleting entry as bulk/individual.

In case some ASIC's does not support this model, they can handle in their SAI.  SAI logical API model is to enforce support this model for future ASIC vendors.  

We have lot other non CRUD API's at present, that should not be reason for deleting this.

**Comment by atitjain** [comment]
@AshokDaparthi 
Inline - 

Intention of these flush API's is to simplify the flush logic when STP state change etc. Instead of sending the FDB entries to removed as bulk or individual entry based on port, vlan , port+vlan or all, they can indicate just port oid, vlan or etc. Then underlying SDK's or hardware will delete those entries. this will be much faster than deleting entry as bulk/individual.
<Atit> I understand the usecase and ASIC implication. Only GAP I have probably is that I have not seen the bulk remove yet. In our SDK (HW assisted) we can do bulk remove and update etc on any set of key values with rest of those masked. 
In case some ASIC's does not support this model, they can handle in their SAI. SAI logical API model is to enforce support this model for future ASIC vendors.

We have lot other non CRUD API's at present, that should not be reason for deleting this.

**Comment by lguohan** [comment]
the bulk remove api will be given a list of fdb entries and then remove. this flush api is to used to remove the fdb entries based on certain attribute of the fdb entries

**Pull request closed without merging**
