### PR TITLE
Add Priority for Tunnel Term Table Entries

### PR DESCRIPTION
**Pull request by mholankar**
Since Tunnel Term Table supports ternary matching for Dest IP+Mask and/or SRC IP+Mask, added priority

### CODE REVIEW

**Comment by mholankar** [comment]
@mikeberesford please take a look

**Comment by mikeberesford** [comment]
@JaiOCP any thoughts?

**Comment by kcudnik** [comment]
to fix errors you will need to squas those commits and force push them on this PR

**Comment by mholankar** [comment]
opening another PR as the commit history in this one is off.

**Pull request closed without merging**
