### PR TITLE
Support update of SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_VR_ID

### PR DESCRIPTION
**Pull request by mholankar**
@mikeberesford @kcudnik @JaiOCP

### CODE REVIEW

**Comment by kcudnik** [comment]
why this change is made ?

**Comment by mholankar** [comment]
@kcudnik - we would like to have the ability to update the VR_ID

**Comment by kcudnik** [comment]
please add proper description and discuss this on SAI Thursday meeting with the community

**Comment by rlhui** [comment]
@JaiOCP , @rck-innovium , would you like to review/approve this? Thanks.

**Review by rck-innovium — APPROVED** [review]

**Review by kcudnik — APPROVED** [review]

**Pull request merged**
