### PR TITLE
Add FDB entry tunnel endpoint IP

### PR DESCRIPTION
**Pull request by itaibaz**

### CODE REVIEW

**Comment by kcudnik** [comment]
Add @default SAI_NULL_OBJECT_ID

**Comment by lguohan** [comment]
but it is not an object id.

**Comment by lguohan** [comment]
@kcudnik, can we condition on SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID/ SAI_BRIDGE_PORT_ATTR_TYPE=SAI_BRIDGE_PORT_TYPE_TUNNEL?

**Comment by kcudnik** [comment]
no, since it's cross attribute condition, metadata is not able to do that

**Comment by kcudnik** [comment]
ahh, it's ip address, then allownull is not required and needs to be removed

**Comment by kcudnik** [comment]
also right now parser don't support default value to be set since this attribute is CREATE_AND_SET what is default value on that attribute ?

**Comment by kcudnik** [comment]
take a look ad #435 and add @default 0.0.0.0 and remove allownull

**Comment by kcudnik** [comment]
you changed that too fast, about 4 hours ago, and @lguohan merged my change 2 hours ago thats why it failed

**Comment by itaibaz** [comment]
Yes, just need to rerun the jenkins job
I ran it on my switch, and it passes

**Pull request merged**
