### PR TITLE
Add attribute for number of available SAs per SC

### PR DESCRIPTION
**Pull request by skbarista**
Add attribute for number of available SAs per SC

### CODE REVIEW

**Review by SarathBug — APPROVED** [review]

**Review by rlhui — APPROVED** [review]

**Comment by rlhui** [comment]
@skbarista  - build failed.

**Comment by skbarista** [comment]
@rlhui I squashed the commits and build looks fine now.

**Comment by JaiOCP** [comment]
@skbarista Sarath, can you respond to my query so that I can close the review

**Comment by skbarista** [comment]
@JaiOCP was there a question for me? I did not see a question in the pr conversations.

**Comment by JaiOCP** [comment]
> Are secure association always power of 2?

@skbarista Hi Sambath, Sorry yes it was a question for you. I have left review comments.

.....snippet...
[JaiOCP](https://github.com/JaiOCP) started a review
Pending 
[inc/saimacsec.h](https://github.com/opencomputeproject/SAI/pull/1420/files/2982618863554d390e7893f5921c76502b6ac13a#diff-ea80e96cf9502e7a75988664e62bf4c4c06dac0ca5008a0702943e81901a3562)
    SAI_MACSEC_MAX_SECURE_ASSOCIATIONS_PER_SC_TWO,
    SAI_MACSEC_MAX_SECURE_ASSOCIATIONS_PER_SC_FOUR,
} sai_macsec_max_secure_associations_per_sc_t;

 
Contributor
@[JaiOCP](https://github.com/JaiOCP)[](https://github.com/judyjoseph)[](https://github.com/SarathBug)[](https://github.com/rlhui)[](https://github.com/rlhui)[](https://github.com/rlhui)[](https://github.com/skbarista)[](https://github.com/skbarista)[](https://github.com/skbarista)[](https://github.com/skbarista)[](https://github.com/JaiOCP) [JaiOCP](https://github.com/JaiOCP)[](https://github.com/skbarista)[](https://github.com/apps/lgtm-com)[](https://github.com/apps/dco)[](https://github.com/apps/azure-pipelines)[](https://github.com/JaiOCP)[](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)[](https://github.com/SarathBug)[](https://github.com/opencomputeproject/SAI/pull/1420/files/2982618863554d390e7893f5921c76502b6ac13a)[](https://github.com/judyjoseph)[](https://github.com/opencomputeproject/SAI/pull/1420/files/2982618863554d390e7893f5921c76502b6ac13a)[](https://github.com/rlhui)[](https://github.com/skbarista)[](https://github.com/rlhui)[](https://github.com/JaiOCP)[](https://github.com/SarathBug)[](https://github.com/judyjoseph)[](https://github.com/) Pending
Are secure association always power of 2?

**Comment by skbarista** [comment]
@JaiOCP I think when I squashed the commit, the comment got lost. Right now the only values for number of secure associations are 2 and 4.

**Comment by JaiOCP** [comment]
> @JaiOCP I think when I squashed the commit, the comment got lost. Right now the only values for number of secure associations are 2 and 4.

Thanks.

**Review by JaiOCP — COMMENTED** [review]
Loos good

**Review by JaiOCP — APPROVED** [review]

**Review by rlhui — APPROVED** [review]

**Pull request merged**
