### PR TITLE
CRM for DASH (#1785)

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**
Add enhancements like read-only attributes and annotations to be used for availability query of DASH objects and entries.

### CODE REVIEW

**Comment by oleksandrivantsiv** [comment]
Cherry-pick missing DASH CRM changes from https://github.com/opencomputeproject/SAI/pull/1785 PR

**Review by marian-pritsak — APPROVED** [review]

**Review by prsunny — APPROVED** [review]

**Comment by kcudnik** [comment]
are those changes made manually or generated from DASH SAI repo?

**Comment by marian-pritsak** [comment]
It's a cherry-pick. They were generated and merged to master originally.

**Comment by oleksandrivantsiv** [comment]
@kcudnik it is a cherry-pick of the https://github.com/opencomputeproject/SAI/pull/1785 PR

**Review by kcudnik — APPROVED** [review]

**Pull request merged**
