### PR TITLE
Decrease PTF init time by enabling only those ports which are used by PTF tests

### PR DESCRIPTION
**Pull request by rspolyak**
- initialize only those ports which were passed to PTF client via command line or as external file
 - remove redundant dictionary front_port_list as it is not in use

### CODE REVIEW

**Comment by lguohan** [comment]
can you merge this into master as well?

**Comment by rspolyak** [comment]
will do the same PR to master branch.

@lguohan Can we merge current one?

**Comment by rspolyak** [comment]
@lguohan is there something that blocks this PR from merge?
I am planning to cherry pick current commit to master branch once this PR is merged to 0.9.6.

**Comment by rspolyak** [comment]
@lguohan  thanks

**Pull request merged**
