### PR TITLE
Updated header file path to fix sonic build issue

### PR DESCRIPTION
**Pull request by vmittal-msft**
Signed-off-by: Vineet Mittal <vineetmittal@microsoft.com>

### CODE REVIEW

**Comment by kcudnik** [comment]
you must fix checkheaders.pl script by adding experimental directory to gcc command:
```
152     system("gcc $src -I. -I '$dir' -o $bin") == 0 or die "gcc failed! $!";
```

**Comment by vmittal-msft** [comment]
> you must fix checkheaders.pl script by adding experimental directory to gcc command:
> 
> ```
> 152     system("gcc $src -I. -I../experimental -I '$dir' -o $bin") == 0 or die "gcc failed! $!";
> ```

Thanks for help.

**Review by kcudnik — APPROVED** [review]

**Comment by kcudnik** [comment]
i think LGTM hang or failed, i can't get status, probably you will need  add empty commit and force push here to retrigger build since /azp run is not working for LGTM

**Comment by ravi861** [comment]
@vmittal-msft Can you please check if the SAI v1.9.1 meta make is still passing with this change? I am running into this problem.
Checking for possible enum values shift (current branch vs origin/master) ...
In file included from ././temp/inc//sai.h:48,
                 from /tmp/ZUnUOwQGIA.c:2:
././temp/inc//saiobject.h:40:10: fatal error: saiexperimentalbmtor.h: No such file or directory
   40 | #include <saiexperimentalbmtor.h>

**Comment by rlhui** [comment]
> @vmittal-msft Can you please check if the SAI v1.9.1 meta make is still passing with this change? I am running into this problem. Checking for possible enum values shift (current branch vs origin/master) ... In file included from ././temp/inc//sai.h:48, from /tmp/ZUnUOwQGIA.c:2: ././temp/inc//saiobject.h:40:10: fatal error: saiexperimentalbmtor.h: No such file or directory 40 | #include <saiexperimentalbmtor.h>

@kcudnik - will you be able to help check this? Thanks.

**Comment by kcudnik** [comment]
where you get this error ?

**Comment by kcudnik** [comment]
i have fix here: https://github.com/kcudnik/SAI/commit/efbc22fcdad827081a053f4043083f8e9ee9a6fc but v1.9.1 its not a branch, its a tag and i cant generate PR for it

**Comment by kcudnik** [comment]
https://github.com/opencomputeproject/SAI/pull/1467

**Comment by ravi861** [comment]
Thanks @kcudnik . I should have been explicit about the tag/branch.
SONiC and other existing users of this tag will still run into above problem when running the checkenumlock.sh script. Is that correct?

**Comment by kcudnik** [comment]
yes

**Pull request merged**
