### PR TITLE
Add hostif trap for HTTP

### PR DESCRIPTION
**Pull request by vivekmoorthy**

### CODE REVIEW

**Comment by vivekmoorthy** [comment]
@mikeberesford

**Review by kcudnik — APPROVED** [review]

**Comment by vivekmoorthy** [comment]
@kcudnik @rlhui Are we good to merge this PR?
Thanks.

**Comment by kcudnik** [comment]
i just signed off for quality, but was this change discussed on SAI weekly meeting?

**Comment by vivekmoorthy** [comment]
No, I will request to add to agenda for this week. Thanks

**Review by JaiOCP — APPROVED** [review]
Looks good

**Pull request merged**
