### PR TITLE
add FEC AN request attribute to saiport.h

### PR DESCRIPTION
**Pull request by shihjeff**

### CODE REVIEW

**Comment by lguohan** [comment]
@shihjeff , check my comments on your other pull request?

**Comment by lguohan** [comment]
is this also dropped?

**Comment by shihjeff** [comment]
@lguohan - yes, this is dropped as well

**Comment by shihjeff** [comment]
Do not merge.  Plan is to finalize the change in 0.9.6 branch (PR# 641) first and then port change here.

**Pull request closed without merging**
