### PR TITLE
Added more ACL test cases

### PR DESCRIPTION
**Pull request by IGordynskyi**
Signed-off-by: Iurii.Gordynskyi Iurii.Gordynskyi@cavium.com

### CODE REVIEW

**Comment by lguohan** [comment]
what's the relation between this one and the #148 ?

**Comment by IGordynskyi** [comment]
We will do changing related to yours comments for #148 step by step using this commit.

**Comment by lguohan** [comment]
Can we close #148 then?

**Comment by IGordynskyi** [comment]
Yes. I think so.

**Comment by IGordynskyi** [comment]
Hello lguohan,
Could we start adding newly developed ACL TC's step by step?
For example, I could create pull request with first 4 or 8 TC's related to action DROP and Forward with changes according to your comments on PR [#148](https://github.com/opencomputeproject/SAI/pull/148).
Let me know your feedback here.

Regards
Iurii

**Comment by lguohan** [comment]
Yes, please.

**Pull request closed without merging**
