### PR TITLE
Enum reordering

### PR DESCRIPTION
**Pull request by shri-khare**

### CODE REVIEW

**Comment by kcudnik** [comment]
what's wrong with current order? why this change?

**Comment by tushar-ty** [comment]
> what's wrong with current order? why this change?

enum type values like SAI_NATIVE_HASH_FIELD_SRC_IPV4 should not change from one spec version to another as that can break any warm upgrade (ISSU).

B/w v1.6.x and v1.8.x some enums are inserted in the middle vs at the end.

subtype enums should always be added to the end of the list.

**Comment by rlhui** [comment]
will you be able to add description of this PR.  Currently it says "No description provided."

**Comment by shri-khare** [comment]
While trying to fix the sanity checks failing here, I accidentally ended up posting another pull request https://github.com/opencomputeproject/SAI/pull/1250. That has the latest changes with all the sanity checks passing. Am closing this request thus in favor of pull request 1250.

**Pull request closed without merging**
