### PR TITLE
Warning: Fix for Unsigned long long usage in 32bit arch

### PR DESCRIPTION
**Pull request by antony-rheneus**
Backported from master branch
https://github.com/opencomputeproject/SAI/commit/500ba4d9eb3b9c3589bef2c6e9618b37a92190db
https://github.com/opencomputeproject/SAI/commit/5d2df184a66b55737892e9433a2c7742376eb424

Signed-off-by: Antony Rheneus <arheneus@marvell.com>

### CODE REVIEW

**Comment by kcudnik** [comment]
retest this please

**Comment by kcudnik** [comment]
since this is 1.4 branch "-I." must be added to Makefile in "perl parse.pl" command, please take a look at Master branch for meta/Makefile

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by kcudnik** [comment]
no, this is comment to @antony-rheneus , Makefile script needs to be updated as in the master, to add -I.

**Comment by antony-rheneus** [comment]
> no, this is comment to @antony-rheneus , Makefile script needs to be updated as in the master, to add -I., take a look at https://github.com/opencomputeproject/SAI/pull/950/files

Oh, ok thanks, I thought comment was not for me. WIll update Makefile

**Pull request merged**
