### PR TITLE
Chained ACL Capability Attr

### PR DESCRIPTION
**Pull request by JaiOCP**
This PR moves the chain acl list information out of sai_acl_capability_t as requested by Kamil for toolchain requirements

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]

**Comment by kcudnik** [comment]
hey, this spouse to fix https://github.com/opencomputeproject/SAI/pull/1787/files which extended attribute value size, and break structures size, but seems like not doing that

**Comment by abdosi** [comment]
@JaiOCP can you please check on Kamil comment.

**Comment by kcudnik** [comment]
the PR i mentioned is changing structure size of sai_attribute_value_t

**Comment by JaiOCP** [comment]
> the PR i mentioned is changing structure size of sai_attribute_value_t

It's not possible to add a new struct without changing sai_attribute_value_t. Isn't this struct used mainly for toolchains? Can we live the change in this struct size.

**Comment by kcudnik** [comment]
yes its possible since thats an union, but by adding bigger struct than entire value, will change size of entire union, and we want to keep union size constant

**Comment by JaiOCP** [comment]
> @JaiOCP can you please check on Kamil comment.

There was a left over field. Deleted it and all should be good now.

**Comment by kcudnik** [comment]
please fix build errors

**Comment by JaiOCP** [comment]
closing this PR as new enums are causing previous commits to conflict.

**Comment by kcudnik** [comment]
you could force push

**Pull request closed without merging**
