### PR TITLE
Added bulk-api for router interface (RIF) object

### PR DESCRIPTION
**Pull request by tejatamboli02**

### CODE REVIEW

**Review by kcudnik — APPROVED** [review]

**Comment by kcudnik** [comment]
Please provide description, also are those bulk functions needed ? do we actually need to have bulk create RIfs ? how many rifs can be created at device ? i understand that this make sense in terms of fdb/route/nexthop etc but rif ?

**Comment by tejatamboli02** [comment]
We dont need bulk functions. It is similar to Tunnel object. This change is just providing apis. Underlying logic calls create one-by-one but still it provides performance improvement over creating multiple RIF objects.

**Comment by kcudnik** [comment]
not sure why this build fails, it complain against sai_attribute_value_t changed, but no changes here, hmm

**Comment by tejatamboli02** [comment]
After updating description, it started failing not sure what is the reason.

**Comment by kcudnik** [comment]
this seems like a some sort of glitch, can you do a force push ?

**Comment by tejatamboli02** [comment]
Done trying again

**Comment by kcudnik** [comment]
i have really no clue why this fails, i just merged -fPIC change and it passed succesfully, could you  try build locally ? "cd SAI/meta; make"

**Comment by tejatamboli02** [comment]
I tried but it keeps giving me doxygen file error. Let me fix it.
SAI/meta$ make
Makefile:70: *** "Missing doxygen in PATH".  Stop.

**Comment by kcudnik** [comment]
> 

you need to install doxygen package dna graphviz package to compile it locally

**Comment by tejatamboli02** [comment]
Closing this pull request as somehow this PR is facing with some compilation errors. Opened a new PR https://github.com/opencomputeproject/SAI/pull/1891 and all checks are passed on this PR. @kcudnik Can you please review this new PR request?

**Pull request closed without merging**
