### PR TITLE
Add SAI_BUFFER_POOL_ATTR_XOFF_SIZE attribute for allocating buffer po…

### PR DESCRIPTION
**Pull request by lguohan**
…ol headroom

### CODE REVIEW

**Comment by lguohan** [comment]
@AshokDaparthi , @kcudnik , please review.

**Comment by lguohan** [comment]
@kcudnik , this commit was lost in commit 072d6147a8409e0b96395cb4bcdf07c5f51b6991

**Comment by AshokDaparthi** [comment]
@lguohan - Could you please add the counters to retrieve the shred headroom counters.

**Comment by lguohan** [comment]
@AshokDaparthi , will do that in a different PR.

**Pull request merged**
