### PR TITLE
add Read-Only SAI_VLAN_ATTR_PORT_LIST to retrive port list for a vlan

### PR DESCRIPTION
**Pull request by lguohan**

### CODE REVIEW

**Comment by itaibaz** [comment]
Hi
Can you explain why do we need both SAI_VLAN_ATTR_MEMBER_LIST and SAI_VLAN_ATTR_PORT_LIST.
If you want the port list, you can read the member list, and then the SAI_VLAN_MEMBER_ATTR_PORT_ID from each member. isn't one of them redundant ?

**Comment by lguohan** [comment]
@atitjain , seems we can get the port list using the member_list. Is that ok if we drop this commit?

**Comment by stcheng** [comment]
agree to have only member list here.

**Comment by atitjain** [comment]
@lguohan I missed the member list part. I am ok with dropping this commit.

**Comment by lguohan** [comment]
unnecessary per discussion

**Pull request closed without merging**
