### PR TITLE
SER Support

### PR DESCRIPTION
**Pull request by JaiOCP**
SER Support is added on top of base infra introduced by
https://github.com/opencomputeproject/SAI/pull/1777

Previous PR is closed as the branch was very old and couldn't reconcile the older commits with enum shifts.
https://github.com/opencomputeproject/SAI/pull/1979
https://github.com/opencomputeproject/SAI/pull/1982

### CODE REVIEW

**Comment by JaiOCP** [comment]
@kcudnik Thrift compiler toolchain is causing the build to fail. Please take a look

**Comment by kcudnik** [comment]
yes, we are aware, not sure yet how to fix that

**Comment by rlhui** [comment]
> @kcudnik Thrift compiler toolchain is causing the build to fail. Please take a look

@JaiOCP it's now fixed.  But this PR is failing metadata check:

updating sai_switch_health_data_t since member count changed from 1 to 2
processing commit bffc28f
ERROR: FATAL: sai_switch_health_data_t members were removed on commit bffc28f, NOT ALLOWED!
make: *** [Makefile:91: all] Error 1

**Comment by JaiOCP** [comment]
I have created a new PR. Could it be something to do with adding exception?On Apr 16, 2024, at 7:52 PM, Rita Hui ***@***.***> wrote:﻿

@kcudnik Thrift compiler toolchain is causing the build to fail. Please take a look

@JaiOCP it's now fixed.  But this PR is failing metadata check:
updating sai_switch_health_data_t since member count changed from 1 to 2
processing commit bffc28f
ERROR: FATAL: sai_switch_health_data_t members were removed on commit bffc28f, NOT ALLOWED!
make: *** [Makefile:91: all] Error 1

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

This electronic communication and the information and any files transmitted with it, or attached to it, are confidential and are intended solely for the use of the individual or entity to whom it is addressed and may contain information that is confidential, legally privileged, protected by privacy laws, or otherwise restricted from disclosure to anyone else. If you are not the intended recipient or the person responsible for delivering the e-mail to the intended recipient, you are hereby notified that any use, copying, distributing, dissemination, forwarding, printing, or copying of this e-mail is strictly prohibited. If you received this e-mail in error, please return the e-mail to the sender, delete it from your computer, and destroy any printed copy of it.

**Comment by kcudnik** [comment]
i pulled your PR, and it passes locally on my machine

**Comment by kcudnik** [comment]
your commit is too far behind, 
```
* ca6b08f (origin/master, origin/HEAD) Update sai version to v1.14.0 (#1991)
* 446b2b7 Upgrade the PR checker's slave container to Bullseye (#1994)
* cd249d6 Modified the test script to match ACL match fields which should be configured to match l4 src and dst port (#1960)
* bffc28f Modified the test file to fix Invalid IP prefix format error while creatimg route entry (#1959)
| * 3e4d429 (1993) SER Support
|/
* d967d23 Add attribute to query the capability of Pre-Ingress ACL stage (#1984)
```

you will need to rebase locally to master, and then force push to PR, then it will pass

**Comment by tjchadaga** [comment]
Approving based on prior approvals in https://github.com/opencomputeproject/SAI/pull/1982 and this comment -https://github.com/opencomputeproject/SAI/pull/1982#issuecomment-2050224649 for backward compatibility.

**Review by tjchadaga — APPROVED** [review]

**Pull request merged**
