### PR TITLE
Create SAI_1.8.1 Release notes.md

### PR DESCRIPTION
**Pull request by kannankvs**
Created SAI_1.8.1 Release notes.md.

### CODE REVIEW

**Comment by rlhui** [comment]
@JaiOCP , @dipankar-ba , @kcudnik , @qbdwlr , @sujinmkang , @mikeberesford , @kperumalbfn  - would you please help review and sign off this release notes for previous SAI header v1.8.1?  Thanks.

**Review by kcudnik — APPROVED** [review]

**Comment by JaiOCP** [comment]
Hi Rita,

Can we review this in Thursday meeting.

I see various enums being added in middle. This will cause the warm boot issue again.

Regards,
-Jai

> On Sep 8, 2021, at 2:05 AM, Kamil Cudnik ***@***.***> wrote:
> 
> ﻿
> @kcudnik approved this pull request.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 

-- 
This electronic communication and the information and any files transmitted 
with it, or attached to it, are confidential and are intended solely for 
the use of the individual or entity to whom it is addressed and may contain 
information that is confidential, legally privileged, protected by privacy 
laws, or otherwise restricted from disclosure to anyone else. If you are 
not the intended recipient or the person responsible for delivering the 
e-mail to the intended recipient, you are hereby notified that any use, 
copying, distributing, dissemination, forwarding, printing, or copying of 
this e-mail is strictly prohibited. If you received this e-mail in error, 
please return the e-mail to the sender, delete it from your computer, and 
destroy any printed copy of it.

**Review by qbdwlr — APPROVED** [review]

**Review by mikeberesford — APPROVED** [review]

**Review by kperumalbfn — APPROVED** [review]

**Review by dipankar-ba — APPROVED** [review]

**Review by sujinmkang — APPROVED** [review]

**Comment by xinliu-seattle** [comment]
@JaiOCP will you be able to sign off? thanks.

**Comment by JaiOCP** [comment]
Hi Xin,

Just closings on some enum reordering issue with Guohan.

Hi Guohan,
Do we want to address the warm boot issue for reordered enums for this release?

Regards,
-Jai

> On Sep 14, 2021, at 9:42 PM, Xin Liu ***@***.***> wrote:
> 
> ﻿
> @JaiOCP will you be able to sign off? thanks.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 

-- 
This electronic communication and the information and any files transmitted 
with it, or attached to it, are confidential and are intended solely for 
the use of the individual or entity to whom it is addressed and may contain 
information that is confidential, legally privileged, protected by privacy 
laws, or otherwise restricted from disclosure to anyone else. If you are 
not the intended recipient or the person responsible for delivering the 
e-mail to the intended recipient, you are hereby notified that any use, 
copying, distributing, dissemination, forwarding, printing, or copying of 
this e-mail is strictly prohibited. If you received this e-mail in error, 
please return the e-mail to the sender, delete it from your computer, and 
destroy any printed copy of it.

**Comment by rlhui** [comment]
> Hi Xin, Just closings on some enum reordering issue with Guohan. Hi Guohan, Do we want to address the warm boot issue for reordered enums for this release? Regards, -Jai
> […](#)
> On Sep 14, 2021, at 9:42 PM, Xin Liu ***@***.***> wrote: ﻿ @JaiOCP will you be able to sign off? thanks. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> -- This electronic communication and the information and any files transmitted with it, or attached to it, are confidential and are intended solely for the use of the individual or entity to whom it is addressed and may contain information that is confidential, legally privileged, protected by privacy laws, or otherwise restricted from disclosure to anyone else. If you are not the intended recipient or the person responsible for delivering the e-mail to the intended recipient, you are hereby notified that any use, copying, distributing, dissemination, forwarding, printing, or copying of this e-mail is strictly prohibited. If you received this e-mail in error, please return the e-mail to the sender, delete it from your computer, and destroy any printed copy of it.

@JaiOCP  - this notes is for SAI v1.8.1, which did not have the enum assignment PR yet.  When the related PRs are back-ported to the v1.8 branch, it'd be v1.8.2. So it's OK that this release notes do not contain enum description.

**Comment by JaiOCP** [comment]
> > Hi Xin, Just closings on some enum reordering issue with Guohan. Hi Guohan, Do we want to address the warm boot issue for reordered enums for this release? Regards, -Jai
> > […](#)
> > On Sep 14, 2021, at 9:42 PM, Xin Liu _**@**_.***> wrote: ﻿ @JaiOCP will you be able to sign off? thanks. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> > -- This electronic communication and the information and any files transmitted with it, or attached to it, are confidential and are intended solely for the use of the individual or entity to whom it is addressed and may contain information that is confidential, legally privileged, protected by privacy laws, or otherwise restricted from disclosure to anyone else. If you are not the intended recipient or the person responsible for delivering the e-mail to the intended recipient, you are hereby notified that any use, copying, distributing, dissemination, forwarding, printing, or copying of this e-mail is strictly prohibited. If you received this e-mail in error, please return the e-mail to the sender, delete it from your computer, and destroy any printed copy of it.
> 
> @JaiOCP - this notes is for SAI v1.8.1, which did not have the enum assignment PR yet. When the related PRs are back-ported to the v1.8 branch, it'd be v1.8.2. So it's OK that this release notes do not contain enum description.

Thanks Rita for clarification.

**Review by JaiOCP — APPROVED** [review]

**Comment by rlhui** [comment]
@kannankvs - would you please help fix DCO error? thanks.

**Pull request merged**
