### PR TITLE
ACL GRE key match

### PR DESCRIPTION
**Pull request by marian-pritsak**
Signed-off-by: Marian Pritsak <marianp@mellanox.com>

### CODE REVIEW

**Comment by marian-pritsak** [comment]
The key is dedicated for GRE packets.
The VNI key should not be used for matching on GRE packets or NVGRE packets.

**Comment by abdosi** [comment]
> The key is dedicated for GRE packets.
> The VNI key should not be used for matching on GRE packets or NVGRE packets.

@marian-pritsak I think we should add in comment section atleast if there is no way to let user know about it.

**Comment by rlhui** [comment]
@JaiOCP , @ashutosh-agrawal, would you please help to review/approve?

**Comment by abdosi** [comment]
@marian-pritsak Please add the comment as mentioned above.

**Comment by rlhui** [comment]
@marian-pritsak , reminder to please address lgtm and build failures.

**Comment by marian-pritsak** [comment]
@abdosi Added comment directly to header

**Pull request merged**
