### PR TITLE
Add label attribute for Policer, RIF, Scheduler and UDF

### PR DESCRIPTION
**Pull request by erohsik**
Add label attribute to a few SAI objects that will help during warmboot object matching.

### CODE REVIEW

**Comment by kcudnik** [comment]
Does this needs to be a string ? Or it would be better to make this uint32 or 64? Maybe it's discussion for sai community meeting

**Comment by erohsik** [comment]
> Does this needs to be a string ? Or it would be better to make this uint32 or 64? Maybe it's discussion for sai community meeting

As discussed in the community meeting, the string provides the option to use the key from the application/config db entry..

**Comment by rlhui** [comment]
@JaiOCP , @rck-innovium , please help review? thanks.

**Review by rck-innovium — APPROVED** [review]

**Review by JaiOCP — APPROVED** [review]

**Comment by tjchadaga** [comment]
@erohsik - could you please resolve branch conflicts?

**Comment by tjchadaga** [comment]
> > > Does this needs to be a string ? Or it would be better to make this uint32 or 64? Maybe it's discussion for sai community meeting
> > 
> > 
> > As discussed in the community meeting, the string provides the option to use the key from the application/config db entry..
> 
> what config db entry ? SAI don't have any idea about any config db entry

@kcudnik - Since the label is populated from the application/NOS, the general consensus was that a string would be easier to manage. Is there a concern with using a string label?

**Comment by kcudnik** [comment]
ok, i got it now it's just a label, please resolve conflicts

**Comment by kcudnik** [comment]
You have spelling issue

**Review by kcudnik — APPROVED** [review]

**Pull request merged**
