### PR TITLE
Move the tunnel decapsulation before L2/L3

### PR DESCRIPTION
**Pull request by marian-pritsak**
Update behavioral model to have decapsulation flow before bridge and router for uniform ingress ACL behavior with  tunnel transit.

### CODE REVIEW

**Review by srikrishnagopu — COMMENTED** [review]
Putting the question here for closure on outer RIF VRF derivation.

Today, RIF provides the VRF in order to perform the tunnel decap and routing lookup. With this model, RIF derivation will be done post tunnel decap but VRF is required for tunnel decap lookup. 

Any thoughts on how we can handle it here ?

**Review by kcudnik — APPROVED** [review]

**Comment by marian-pritsak** [comment]
> Putting the question here for closure on outer RIF VRF derivation.
> 
> Today, RIF provides the VRF in order to perform the tunnel decap and routing lookup. With this model, RIF derivation will be done post tunnel decap but VRF is required for tunnel decap lookup.
> 
> Any thoughts on how we can handle it here ?

Yes, I'd like to deprecate tunnel term entry VR_ID attribute as it does not make sense in this proposed model.

**Comment by mholankar** [comment]
This change in the model impacts our current usage of Tunnel Decap. What is the plan for backward compatibility?

**Comment by mholankar** [comment]
I discussed with our team, and we are ok with deprecating the tunnel term entry VR_ID attribute.

**Review by kperumalbfn — APPROVED** [review]

**Review by srikrishnagopu — APPROVED** [review]

**Comment by kcudnik** [comment]
please resolve conflicts

**Comment by marian-pritsak** [comment]
TODO: What happens to mymac lookup?

**Comment by KrisNey-MSFT** [comment]
Need Fred's GitHub account (Yue Gao) to review and approve.

**Comment by kcudnik** [comment]
you will need to squash commits to 1

**Review by JaiOCP — APPROVED** [review]
Looks Good

**Comment by BYGX-wcr** [comment]
@marian-pritsak , Did your Markdown file reference to a wrong pipeline model file? You added pipeline_v11 but referred to pipeline_v10

**Pull request merged**
